kinematic_model: "four_wheel"
drive_arc_topic: "/navigator/drive_arc"
wheels_topic: "/joy"
motor_factor: 1.0

four_wheel:
    width: 0.42195
    length: 0.2222
    height: 0.0745
    radius: 0.1016 
    contact_constraints:
        vxl: -0.0065
        vxr: -0.0075

two_wheel:
    length: 0.1
    width: 0.25
    height: 0.4
    radius: 0.2
