kinematic_model: "four_wheel"
drive_arc_topic: "/navigator/drive_arc"
wheels_topic: "/joy"
motor_factor: 1.0

four_wheel:
    width: 0.32195
    length: 0.2222
    height: 0.0745
    radius: 0.0955
    contact_constraints:
        vx: 0
        vy: 0

two_wheel:
    length: 0.1
    width: 0.25
    height: 0.4
    radius: 0.2
